# Generated by Django 5.2 on 2025-05-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_items_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_occupied',
        ),
    ]
